---
- name: Install packages for building source code
  apt:
    name: "{{ packages_list_for_build }}"
    state: present

- name: Clone source git repository
  git:
    repo: https://github.com/peervpn/peervpn.git
    dest: "{{playbook_dir}}/peervpn_source_code"

- name: Build source code
  make:
    chdir: "{{playbook_dir}}/peervpn_source_code"

- name: Create directory sctructure for creating deb package
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
    mode: '0755'
  loop:
    - "{{playbook_dir}}/peervpn_{{peervpn_deb_package_version}}_{{peervpn_deb_package_architecture}}/usr/local/bin"
    - "{{playbook_dir}}/peervpn_{{peervpn_deb_package_version}}_{{peervpn_deb_package_architecture}}/DEBIAN"

- name: Copy executable file to working directory for deb package
  copy: 
    src: "{{playbook_dir}}/peervpn_source_code/peervpn"
    dest: "{{playbook_dir}}/peervpn_{{peervpn_deb_package_version}}_{{peervpn_deb_package_architecture}}/usr/local/bin/"

- name: Create control file for deb package
  copy:
    dest: "{{playbook_dir}}/peervpn_{{peervpn_deb_package_version}}_{{peervpn_deb_package_architecture}}/DEBIAN/control"
    content: |
      Package: peervpn
      Version: {{peervpn_deb_package_version}}
      Architecture: {{peervpn_deb_package_architecture}}
      Maintainer: Aleksei Kabarukhin <akabarukhin@gmail.com>
      Description: The open source [peer-to-peer VPN](https://peervpn.net/)
       Original Code: https://github.com/peervpn/peervpn
       Tutorial: https://peervpn.net/tutorial/

- name: Create deb package
  shell: "dpkg-deb --build --root-owner-group {{playbook_dir}}/peervpn_{{peervpn_deb_package_version}}_{{peervpn_deb_package_architecture}}"

# !! In the case of a repository located on the other server then the code below should be rewritten !!
- name: Ensure that target directory in repo is exist
  file:
    path: "{{repo_base_path}}/{{peervpn_deb_package_architecture}}"
    recurse: yes
    state: directory
    mode: '0755'
- name: Copy package to local repo
  copy: 
    src: "{{playbook_dir}}/peervpn_{{peervpn_deb_package_version}}_{{peervpn_deb_package_architecture}}.deb"
    dest: "{{repo_base_path}}/{{peervpn_deb_package_architecture}}/peervpn_{{peervpn_deb_package_version}}_{{peervpn_deb_package_architecture}}.deb"

- name: Run dpkg-scanpackages
  shell: "cd {{repo_base_path}} && dpkg-scanpackages {{peervpn_deb_package_architecture}} | gzip -9c > {{repo_base_path}}/{{peervpn_deb_package_architecture}}/Packages.gz"

- name: Add localhost as packages source to file /etc/apt/sources.list
  lineinfile:
    dest: /etc/apt/sources.list
    line: "deb [trusted=yes] http://{{repo_host}}/debs {{peervpn_deb_package_architecture}}/"
