---
- name: Include tasks for building source
  include_tasks:
    file: build.yml
    apply:
      tags:
        - build
  tags:
    - build

- name: Include tasks for installing package
  include_tasks:
    file: install-package.yml
    apply:
      tags:
        - install
  tags: [ install ]
